/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposIndexRouteImport } from './routes/repos/index'
import { Route as ReposNewRouteImport } from './routes/repos.new'
import { Route as JobsJob_idRouteImport } from './routes/jobs.$job_id'
import { Route as ReposOwnerNameRouteImport } from './routes/repos/$owner.$name'
import { Route as CommitsOwnerNameHashRouteImport } from './routes/commits.$owner.$name.$hash'
import { Route as BlobOwnerNameHashRouteImport } from './routes/blob.$owner.$name.$hash'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposNewRoute = ReposNewRouteImport.update({
  id: '/repos/new',
  path: '/repos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJob_idRoute = JobsJob_idRouteImport.update({
  id: '/jobs/$job_id',
  path: '/jobs/$job_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerNameRoute = ReposOwnerNameRouteImport.update({
  id: '/repos/$owner/$name',
  path: '/repos/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitsOwnerNameHashRoute = CommitsOwnerNameHashRouteImport.update({
  id: '/commits/$owner/$name/$hash',
  path: '/commits/$owner/$name/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const BlobOwnerNameHashRoute = BlobOwnerNameHashRouteImport.update({
  id: '/blob/$owner/$name/$hash',
  path: '/blob/$owner/$name/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/$job_id': typeof JobsJob_idRoute
  '/repos/new': typeof ReposNewRoute
  '/repos/': typeof ReposIndexRoute
  '/repos/$owner/$name': typeof ReposOwnerNameRoute
  '/blob/$owner/$name/$hash': typeof BlobOwnerNameHashRoute
  '/commits/$owner/$name/$hash': typeof CommitsOwnerNameHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/$job_id': typeof JobsJob_idRoute
  '/repos/new': typeof ReposNewRoute
  '/repos': typeof ReposIndexRoute
  '/repos/$owner/$name': typeof ReposOwnerNameRoute
  '/blob/$owner/$name/$hash': typeof BlobOwnerNameHashRoute
  '/commits/$owner/$name/$hash': typeof CommitsOwnerNameHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/$job_id': typeof JobsJob_idRoute
  '/repos/new': typeof ReposNewRoute
  '/repos/': typeof ReposIndexRoute
  '/repos/$owner/$name': typeof ReposOwnerNameRoute
  '/blob/$owner/$name/$hash': typeof BlobOwnerNameHashRoute
  '/commits/$owner/$name/$hash': typeof CommitsOwnerNameHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/jobs/$job_id'
    | '/repos/new'
    | '/repos/'
    | '/repos/$owner/$name'
    | '/blob/$owner/$name/$hash'
    | '/commits/$owner/$name/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/jobs/$job_id'
    | '/repos/new'
    | '/repos'
    | '/repos/$owner/$name'
    | '/blob/$owner/$name/$hash'
    | '/commits/$owner/$name/$hash'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/jobs/$job_id'
    | '/repos/new'
    | '/repos/'
    | '/repos/$owner/$name'
    | '/blob/$owner/$name/$hash'
    | '/commits/$owner/$name/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  JobsJob_idRoute: typeof JobsJob_idRoute
  ReposNewRoute: typeof ReposNewRoute
  ReposIndexRoute: typeof ReposIndexRoute
  ReposOwnerNameRoute: typeof ReposOwnerNameRoute
  BlobOwnerNameHashRoute: typeof BlobOwnerNameHashRoute
  CommitsOwnerNameHashRoute: typeof CommitsOwnerNameHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/new': {
      id: '/repos/new'
      path: '/repos/new'
      fullPath: '/repos/new'
      preLoaderRoute: typeof ReposNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$job_id': {
      id: '/jobs/$job_id'
      path: '/jobs/$job_id'
      fullPath: '/jobs/$job_id'
      preLoaderRoute: typeof JobsJob_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$name': {
      id: '/repos/$owner/$name'
      path: '/repos/$owner/$name'
      fullPath: '/repos/$owner/$name'
      preLoaderRoute: typeof ReposOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commits/$owner/$name/$hash': {
      id: '/commits/$owner/$name/$hash'
      path: '/commits/$owner/$name/$hash'
      fullPath: '/commits/$owner/$name/$hash'
      preLoaderRoute: typeof CommitsOwnerNameHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blob/$owner/$name/$hash': {
      id: '/blob/$owner/$name/$hash'
      path: '/blob/$owner/$name/$hash'
      fullPath: '/blob/$owner/$name/$hash'
      preLoaderRoute: typeof BlobOwnerNameHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  JobsJob_idRoute: JobsJob_idRoute,
  ReposNewRoute: ReposNewRoute,
  ReposIndexRoute: ReposIndexRoute,
  ReposOwnerNameRoute: ReposOwnerNameRoute,
  BlobOwnerNameHashRoute: BlobOwnerNameHashRoute,
  CommitsOwnerNameHashRoute: CommitsOwnerNameHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
