/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposIndexRouteImport } from './routes/repos/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ReposNewRouteImport } from './routes/repos.new'
import { Route as RecipesBuilderRouteImport } from './routes/recipes/builder'
import { Route as JobsJob_idRouteImport } from './routes/jobs/$job_id'
import { Route as ReposOwnerNameRouteImport } from './routes/repos/$owner.$name'
import { Route as SnapshotsOwnerNameHashRouteImport } from './routes/snapshots/$owner.$name.$hash'
import { Route as ReposOwnerNamePdfMineruRouteImport } from './routes/repos/$owner.$name/pdf-mineru'
import { Route as BlobOwnerNameHashRouteImport } from './routes/blob.$owner.$name.$hash'
import { Route as SnapshotsOwnerNameHashRowsRouteImport } from './routes/snapshots/$owner.$name.$hash/rows'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIndexRoute = ReposIndexRouteImport.update({
  id: '/repos/',
  path: '/repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposNewRoute = ReposNewRouteImport.update({
  id: '/repos/new',
  path: '/repos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesBuilderRoute = RecipesBuilderRouteImport.update({
  id: '/recipes/builder',
  path: '/recipes/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJob_idRoute = JobsJob_idRouteImport.update({
  id: '/jobs/$job_id',
  path: '/jobs/$job_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerNameRoute = ReposOwnerNameRouteImport.update({
  id: '/repos/$owner/$name',
  path: '/repos/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsOwnerNameHashRoute = SnapshotsOwnerNameHashRouteImport.update({
  id: '/snapshots/$owner/$name/$hash',
  path: '/snapshots/$owner/$name/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerNamePdfMineruRoute = ReposOwnerNamePdfMineruRouteImport.update({
  id: '/pdf-mineru',
  path: '/pdf-mineru',
  getParentRoute: () => ReposOwnerNameRoute,
} as any)
const BlobOwnerNameHashRoute = BlobOwnerNameHashRouteImport.update({
  id: '/blob/$owner/$name/$hash',
  path: '/blob/$owner/$name/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsOwnerNameHashRowsRoute =
  SnapshotsOwnerNameHashRowsRouteImport.update({
    id: '/rows',
    path: '/rows',
    getParentRoute: () => SnapshotsOwnerNameHashRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/$job_id': typeof JobsJob_idRoute
  '/recipes/builder': typeof RecipesBuilderRoute
  '/repos/new': typeof ReposNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/repos/': typeof ReposIndexRoute
  '/repos/$owner/$name': typeof ReposOwnerNameRouteWithChildren
  '/blob/$owner/$name/$hash': typeof BlobOwnerNameHashRoute
  '/repos/$owner/$name/pdf-mineru': typeof ReposOwnerNamePdfMineruRoute
  '/snapshots/$owner/$name/$hash': typeof SnapshotsOwnerNameHashRouteWithChildren
  '/snapshots/$owner/$name/$hash/rows': typeof SnapshotsOwnerNameHashRowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/$job_id': typeof JobsJob_idRoute
  '/recipes/builder': typeof RecipesBuilderRoute
  '/repos/new': typeof ReposNewRoute
  '/jobs': typeof JobsIndexRoute
  '/repos': typeof ReposIndexRoute
  '/repos/$owner/$name': typeof ReposOwnerNameRouteWithChildren
  '/blob/$owner/$name/$hash': typeof BlobOwnerNameHashRoute
  '/repos/$owner/$name/pdf-mineru': typeof ReposOwnerNamePdfMineruRoute
  '/snapshots/$owner/$name/$hash': typeof SnapshotsOwnerNameHashRouteWithChildren
  '/snapshots/$owner/$name/$hash/rows': typeof SnapshotsOwnerNameHashRowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/$job_id': typeof JobsJob_idRoute
  '/recipes/builder': typeof RecipesBuilderRoute
  '/repos/new': typeof ReposNewRoute
  '/jobs/': typeof JobsIndexRoute
  '/repos/': typeof ReposIndexRoute
  '/repos/$owner/$name': typeof ReposOwnerNameRouteWithChildren
  '/blob/$owner/$name/$hash': typeof BlobOwnerNameHashRoute
  '/repos/$owner/$name/pdf-mineru': typeof ReposOwnerNamePdfMineruRoute
  '/snapshots/$owner/$name/$hash': typeof SnapshotsOwnerNameHashRouteWithChildren
  '/snapshots/$owner/$name/$hash/rows': typeof SnapshotsOwnerNameHashRowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/jobs/$job_id'
    | '/recipes/builder'
    | '/repos/new'
    | '/jobs/'
    | '/repos/'
    | '/repos/$owner/$name'
    | '/blob/$owner/$name/$hash'
    | '/repos/$owner/$name/pdf-mineru'
    | '/snapshots/$owner/$name/$hash'
    | '/snapshots/$owner/$name/$hash/rows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/jobs/$job_id'
    | '/recipes/builder'
    | '/repos/new'
    | '/jobs'
    | '/repos'
    | '/repos/$owner/$name'
    | '/blob/$owner/$name/$hash'
    | '/repos/$owner/$name/pdf-mineru'
    | '/snapshots/$owner/$name/$hash'
    | '/snapshots/$owner/$name/$hash/rows'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/jobs/$job_id'
    | '/recipes/builder'
    | '/repos/new'
    | '/jobs/'
    | '/repos/'
    | '/repos/$owner/$name'
    | '/blob/$owner/$name/$hash'
    | '/repos/$owner/$name/pdf-mineru'
    | '/snapshots/$owner/$name/$hash'
    | '/snapshots/$owner/$name/$hash/rows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  JobsJob_idRoute: typeof JobsJob_idRoute
  RecipesBuilderRoute: typeof RecipesBuilderRoute
  ReposNewRoute: typeof ReposNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ReposIndexRoute: typeof ReposIndexRoute
  ReposOwnerNameRoute: typeof ReposOwnerNameRouteWithChildren
  BlobOwnerNameHashRoute: typeof BlobOwnerNameHashRoute
  SnapshotsOwnerNameHashRoute: typeof SnapshotsOwnerNameHashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/': {
      id: '/repos/'
      path: '/repos'
      fullPath: '/repos/'
      preLoaderRoute: typeof ReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/new': {
      id: '/repos/new'
      path: '/repos/new'
      fullPath: '/repos/new'
      preLoaderRoute: typeof ReposNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/builder': {
      id: '/recipes/builder'
      path: '/recipes/builder'
      fullPath: '/recipes/builder'
      preLoaderRoute: typeof RecipesBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$job_id': {
      id: '/jobs/$job_id'
      path: '/jobs/$job_id'
      fullPath: '/jobs/$job_id'
      preLoaderRoute: typeof JobsJob_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$name': {
      id: '/repos/$owner/$name'
      path: '/repos/$owner/$name'
      fullPath: '/repos/$owner/$name'
      preLoaderRoute: typeof ReposOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots/$owner/$name/$hash': {
      id: '/snapshots/$owner/$name/$hash'
      path: '/snapshots/$owner/$name/$hash'
      fullPath: '/snapshots/$owner/$name/$hash'
      preLoaderRoute: typeof SnapshotsOwnerNameHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$name/pdf-mineru': {
      id: '/repos/$owner/$name/pdf-mineru'
      path: '/pdf-mineru'
      fullPath: '/repos/$owner/$name/pdf-mineru'
      preLoaderRoute: typeof ReposOwnerNamePdfMineruRouteImport
      parentRoute: typeof ReposOwnerNameRoute
    }
    '/blob/$owner/$name/$hash': {
      id: '/blob/$owner/$name/$hash'
      path: '/blob/$owner/$name/$hash'
      fullPath: '/blob/$owner/$name/$hash'
      preLoaderRoute: typeof BlobOwnerNameHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots/$owner/$name/$hash/rows': {
      id: '/snapshots/$owner/$name/$hash/rows'
      path: '/rows'
      fullPath: '/snapshots/$owner/$name/$hash/rows'
      preLoaderRoute: typeof SnapshotsOwnerNameHashRowsRouteImport
      parentRoute: typeof SnapshotsOwnerNameHashRoute
    }
  }
}

interface ReposOwnerNameRouteChildren {
  ReposOwnerNamePdfMineruRoute: typeof ReposOwnerNamePdfMineruRoute
}

const ReposOwnerNameRouteChildren: ReposOwnerNameRouteChildren = {
  ReposOwnerNamePdfMineruRoute: ReposOwnerNamePdfMineruRoute,
}

const ReposOwnerNameRouteWithChildren = ReposOwnerNameRoute._addFileChildren(
  ReposOwnerNameRouteChildren,
)

interface SnapshotsOwnerNameHashRouteChildren {
  SnapshotsOwnerNameHashRowsRoute: typeof SnapshotsOwnerNameHashRowsRoute
}

const SnapshotsOwnerNameHashRouteChildren: SnapshotsOwnerNameHashRouteChildren =
  {
    SnapshotsOwnerNameHashRowsRoute: SnapshotsOwnerNameHashRowsRoute,
  }

const SnapshotsOwnerNameHashRouteWithChildren =
  SnapshotsOwnerNameHashRoute._addFileChildren(
    SnapshotsOwnerNameHashRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  JobsJob_idRoute: JobsJob_idRoute,
  RecipesBuilderRoute: RecipesBuilderRoute,
  ReposNewRoute: ReposNewRoute,
  JobsIndexRoute: JobsIndexRoute,
  ReposIndexRoute: ReposIndexRoute,
  ReposOwnerNameRoute: ReposOwnerNameRouteWithChildren,
  BlobOwnerNameHashRoute: BlobOwnerNameHashRoute,
  SnapshotsOwnerNameHashRoute: SnapshotsOwnerNameHashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
