/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create User */
        post: operations["create_user_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_admin_users__user_id__patch"];
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repos */
        get: operations["list_repos_repos_get"];
        put?: never;
        /** Create Repo */
        post: operations["create_repo_repos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repo */
        get: operations["get_repo_repos__owner___name__get"];
        put?: never;
        post?: never;
        /** Delete Repo */
        delete: operations["delete_repo_repos__owner___name__delete"];
        options?: never;
        head?: never;
        /** Update Repo */
        patch: operations["update_repo_repos__owner___name__patch"];
        trace?: never;
    };
    "/repos/{owner}/{name}/blobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Blob */
        post: operations["upload_blob_repos__owner___name__blobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}/blobs/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Blob */
        get: operations["download_blob_repos__owner___name__blobs__sha256__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Commit */
        post: operations["create_commit_repos__owner___name__commits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}/commits/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Commit */
        get: operations["get_commit_repos__owner___name__commits__hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_repos__owner___name__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{owner}/{name}/tree/{commit_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tree */
        get: operations["get_tree_repos__owner___name__tree__commit_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthenticatedUser
         * @description 认证通过后的用户视图（不含密码 hash）。
         */
        AuthenticatedUser: {
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
        };
        /** BlobUploadResponse */
        BlobUploadResponse: {
            /** Deduplicated */
            deduplicated: boolean;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
            /** Storage Key */
            storage_key: string;
        };
        /** CommitCreate */
        CommitCreate: {
            /** Author Id */
            author_id: string;
            lineage?: components["schemas"]["Lineage"] | null;
            /** Message */
            message?: string | null;
            /** Parents */
            parents?: string[];
            /** Ref */
            ref?: string | null;
            tree: components["schemas"]["TreeCreate"];
        };
        /** CommitRead */
        CommitRead: {
            /** Author Id */
            author_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deduplicated */
            deduplicated: boolean;
            /** Hash */
            hash: string;
            lineage: components["schemas"]["Lineage"] | null;
            /** Message */
            message: string | null;
            /** Parents */
            parents: string[];
            /** Repo Id */
            repo_id: string;
            tree: components["schemas"]["TreeRead"];
            /** Tree Hash */
            tree_hash: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Email */
            email?: string | null;
            /** External Id */
            external_id?: string | null;
            /** Password */
            password?: string | null;
            /**
             * Role
             * @default user
             * @enum {string}
             */
            role: "admin" | "user";
            /** Username */
            username: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Adapter Name */
            adapter_name: string;
            /** Adapter Version */
            adapter_version: string;
            /** Author Id */
            author_id: string;
            /** Message */
            message?: string | null;
            /** Parents */
            parents?: string[];
            /** Ref */
            ref?: string | null;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
        };
        /** IngestResponse */
        IngestResponse: {
            commit: components["schemas"]["CommitRead"];
            ingest_summary: components["schemas"]["IngestSummary"];
        };
        /** IngestSummary */
        IngestSummary: {
            /**
             * Asset Count
             * @default 0
             */
            asset_count: number;
            /**
             * Bytes Written
             * @default 0
             */
            bytes_written: number;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /** Notes */
            notes?: string | null;
        };
        /** InputRef */
        InputRef: {
            /** Commit */
            commit: string;
            /**
             * Repo
             * @description 上游 repository 的 fully qualified id
             */
            repo: string;
        };
        /** Lineage */
        Lineage: {
            /**
             * Env
             * @description 运行环境：python 版本、model id（LLM）、依赖摘要等
             */
            env?: {
                [key: string]: unknown;
            };
            /**
             * Inputs
             * @description 本 commit 的上游 commits；adapter 产出的 Bronze 通常为空
             */
            inputs?: components["schemas"]["InputRef"][];
            produced_by: components["schemas"]["ProducedBy"];
            /** Run Id */
            run_id: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** ProducedBy */
        ProducedBy: {
            /** Config Hash */
            config_hash: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "adapter" | "processor" | "manual";
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** RepositoryCreate */
        RepositoryCreate: {
            /** Description */
            description?: string | null;
            /**
             * Layer
             * @enum {string}
             */
            layer: "bronze" | "silver" | "gold";
            /** Name */
            name: string;
            /** Owner */
            owner: string;
            /** Subtype */
            subtype: ("pdf" | "pdf-collection" | "webpage" | "webpage-collection" | "book" | "image-set") | ("text-corpus" | "qa-records" | "dialog-corpus" | "image-text-pairs") | ("cpt" | "sft" | "dpo" | "rlhf-pref" | "eval");
            /**
             * Visibility
             * @default private
             * @enum {string}
             */
            visibility: "private" | "internal" | "public";
        };
        /**
         * RepositoryListItem
         * @description list 响应的简化条目（与 Read 字段相同，但单独类型便于后续演进）。
         */
        RepositoryListItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /**
             * Layer
             * @enum {string}
             */
            layer: "bronze" | "silver" | "gold";
            /** Name */
            name: string;
            /** Owner */
            owner: string;
            /** Subtype */
            subtype: ("pdf" | "pdf-collection" | "webpage" | "webpage-collection" | "book" | "image-set") | ("text-corpus" | "qa-records" | "dialog-corpus" | "image-text-pairs") | ("cpt" | "sft" | "dpo" | "rlhf-pref" | "eval");
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "private" | "internal" | "public";
        };
        /**
         * RepositoryListResponse
         * @description GET /repos 响应。
         */
        RepositoryListResponse: {
            /** Items */
            items: components["schemas"]["RepositoryListItem"][];
            /** Total */
            total: number;
        };
        /** RepositoryRead */
        RepositoryRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /**
             * Layer
             * @enum {string}
             */
            layer: "bronze" | "silver" | "gold";
            /** Name */
            name: string;
            /** Owner */
            owner: string;
            /** Subtype */
            subtype: ("pdf" | "pdf-collection" | "webpage" | "webpage-collection" | "book" | "image-set") | ("text-corpus" | "qa-records" | "dialog-corpus" | "image-text-pairs") | ("cpt" | "sft" | "dpo" | "rlhf-pref" | "eval");
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "private" | "internal" | "public";
        };
        /**
         * RepositoryUpdate
         * @description PATCH partial update：全 Optional 默认 None；只更新非 None 字段。
         *
         *     spec MUST FIX #4：避免误清——None 表示"未传"而非"清空"。
         */
        RepositoryUpdate: {
            /** Description */
            description?: string | null;
            /** Visibility */
            visibility?: ("private" | "internal" | "public") | null;
        };
        /** TreeCreate */
        TreeCreate: {
            /** Entries */
            entries: components["schemas"]["TreeEntryCreate"][];
        };
        /** TreeEntryCreate */
        TreeEntryCreate: {
            /**
             * Entry Type
             * @default blob
             * @constant
             */
            entry_type: "blob";
            /** Mode */
            mode: number;
            /** Name */
            name: string;
            /** Target Hash */
            target_hash: string;
        };
        /** TreeEntryRead */
        TreeEntryRead: {
            /**
             * Entry Type
             * @constant
             */
            entry_type: "blob";
            /** Mode */
            mode: number;
            /** Name */
            name: string;
            /** Target Hash */
            target_hash: string;
        };
        /** TreeRead */
        TreeRead: {
            /** Entries */
            entries: components["schemas"]["TreeEntryRead"][];
            /** Hash */
            hash: string;
        };
        /** UpdateUserRequest */
        UpdateUserRequest: {
            /** Is Active */
            is_active?: boolean | null;
            /** New Password */
            new_password?: string | null;
            /** Role */
            role?: ("admin" | "user") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_user_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_repos_repos_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                layer?: ("bronze" | "silver" | "gold") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_repo_repos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repo_repos__owner___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_repo_repos__owner___name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_repo_repos__owner___name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_blob_repos__owner___name__blobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlobUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_blob_repos__owner___name__blobs__sha256__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_commit_repos__owner___name__commits_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_commit_repos__owner___name__commits__hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_repos__owner___name__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tree_repos__owner___name__tree__commit_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                name: string;
                commit_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
